import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Picky Picky Picky Import Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Picky Picky Picky Importer
        </h1>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>
            <h2>Dashboard &rarr;</h2>
            <p className={ styles.text }>Here</p>
          </a>

          <a href="/import" className={styles.card}>
            <h2>Import &rarr;</h2>
            <p className={ styles.text }>Import Vendor File - Export POS and Shopify files</p>
          </a>

          <a href="/vendors" className={styles.card}>
            <h2>Vendors &rarr;</h2>
            <p className={ styles.text }>Add vendor data</p>
          </a>

          <a href="/colors" className={styles.card}>
            <h2>Colors &rarr;</h2>
            <p className={ styles.text }>Set the special color words to be replaced when we are importing to POS files</p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
