import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Picky Picky Picky Import Converter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Picky Picky Picky Importer
        </h1>

        <p className={styles.description}>
          inventory converter
        </p>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>
            <h2>Dashboard &rarr;</h2>
            <p>Here</p>
          </a>

          <a href="/import" className={styles.card}>
            <h2>Import &rarr;</h2>
            <p>Import Vendor File - Export POS and Shopify files</p>
          </a>

          <a href="/vendors" className={styles.card}>
            <h2>Vendors &rarr;</h2>
            <p>Add vendor data</p>
          </a>

          <a href="/colors" className={styles.card}>
            <h2>Colors &rarr;</h2>
            <p>Set the special color words to be replaced when we are importing to POS files</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
